import { SdkEvent } from '@openim/wasm-client-sdk';

// Keep this order byte-for-byte aligned with openim-sdk-cpp/go/constant.go.
export enum NativeEvent {
  CONNECTING,
  CONNECT_SUCCESS,
  CONNECT_FAILED,
  KICKED_OFFLINE,
  USER_TOKEN_EXPIRED,
  JOINED_GROUP_ADDED,
  JOINED_GROUP_DELETED,
  GROUP_MEMBER_ADDED,
  GROUP_MEMBER_DELETED,
  GROUP_APPLICATION_ADDED,
  GROUP_APPLICATION_DELETED,
  GROUP_INFO_CHANGED,
  GROUP_DISMISSED,
  GROUP_MEMBER_INFO_CHANGED,
  GROUP_APPLICATION_ACCEPTED,
  GROUP_APPLICATION_REJECTED,
  FRIEND_APPLICATION_ADDED,
  FRIEND_APPLICATION_DELETED,
  FRIEND_APPLICATION_ACCEPTED,
  FRIEND_APPLICATION_REJECTED,
  FRIEND_ADDED,
  FRIEND_DELETED,
  FRIEND_INFO_CHANGED,
  BLACK_ADDED,
  BLACK_DELETED,
  SYNC_SERVER_START,
  SYNC_SERVER_FINISH,
  SYNC_SERVER_PROGRESS,
  SYNC_SERVER_FAILED,
  NEW_CONVERSATION,
  CONVERSATION_CHANGED,
  TOTAL_UNREAD_MESSAGE_COUNT_CHANGED,
  RECV_NEW_MESSAGE,
  RECV_C2C_READ_RECEIPT,
  RECV_GROUP_READ_RECEIPT,
  NEW_RECV_MESSAGE_REVOKED,
  RECV_MESSAGE_EXTENSIONS_CHANGED,
  RECV_MESSAGE_EXTENSIONS_DELETED,
  RECV_MESSAGE_EXTENSIONS_ADDED,
  RECV_OFFLINE_NEW_MESSAGE,
  MSG_DELETED,
  RECV_NEW_MESSAGES,
  RECV_OFFLINE_NEW_MESSAGES,
  SELF_INFO_UPDATED,
  USER_STATUS_CHANGED,
  RECV_CUSTOM_BUSINESS_MESSAGE,
  MESSAGE_KV_INFO_CHANGED,
  OPEN,
  PART_SIZE,
  HASH_PART_PROGRESS,
  HASH_PART_COMPLETE,
  UPLOAD_ID,
  UPLOAD_PART_COMPLETE,
  UPLOAD_COMPLETE,
  COMPLETE,
  CONVERSATION_USER_INPUT_STATUS_CHANGED,
  RECV_ONLINE_ONLY_MESSAGE,
  USER_TOKEN_INVALID,
  ON_PROGRESS,
}

export const eventMapping: Partial<Record<NativeEvent, SdkEvent>> = {
  [NativeEvent.CONNECTING]: SdkEvent.OnConnecting,
  [NativeEvent.CONNECT_SUCCESS]: SdkEvent.OnConnectSuccess,
  [NativeEvent.CONNECT_FAILED]: SdkEvent.OnConnectFailed,
  [NativeEvent.KICKED_OFFLINE]: SdkEvent.OnKickedOffline,
  [NativeEvent.USER_TOKEN_EXPIRED]: SdkEvent.OnUserTokenExpired,
  [NativeEvent.USER_TOKEN_INVALID]: SdkEvent.OnUserTokenInvalid,
  [NativeEvent.JOINED_GROUP_ADDED]: SdkEvent.OnJoinedGroupAdded,
  [NativeEvent.JOINED_GROUP_DELETED]: SdkEvent.OnJoinedGroupDeleted,
  [NativeEvent.GROUP_MEMBER_ADDED]: SdkEvent.OnGroupMemberAdded,
  [NativeEvent.GROUP_MEMBER_DELETED]: SdkEvent.OnGroupMemberDeleted,
  [NativeEvent.GROUP_APPLICATION_ADDED]: SdkEvent.OnGroupApplicationAdded,
  [NativeEvent.GROUP_APPLICATION_DELETED]: SdkEvent.OnGroupApplicationDeleted,
  [NativeEvent.GROUP_INFO_CHANGED]: SdkEvent.OnGroupInfoChanged,
  [NativeEvent.GROUP_DISMISSED]: SdkEvent.OnGroupDismissed,
  [NativeEvent.GROUP_MEMBER_INFO_CHANGED]: SdkEvent.OnGroupMemberInfoChanged,
  [NativeEvent.GROUP_APPLICATION_ACCEPTED]: SdkEvent.OnGroupApplicationAccepted,
  [NativeEvent.GROUP_APPLICATION_REJECTED]: SdkEvent.OnGroupApplicationRejected,
  [NativeEvent.FRIEND_APPLICATION_ADDED]: SdkEvent.OnFriendApplicationAdded,
  [NativeEvent.FRIEND_APPLICATION_DELETED]: SdkEvent.OnFriendApplicationDeleted,
  [NativeEvent.FRIEND_APPLICATION_ACCEPTED]:
    SdkEvent.OnFriendApplicationAccepted,
  [NativeEvent.FRIEND_APPLICATION_REJECTED]:
    SdkEvent.OnFriendApplicationRejected,
  [NativeEvent.FRIEND_ADDED]: SdkEvent.OnFriendAdded,
  [NativeEvent.FRIEND_DELETED]: SdkEvent.OnFriendDeleted,
  [NativeEvent.FRIEND_INFO_CHANGED]: SdkEvent.OnFriendInfoChanged,
  [NativeEvent.BLACK_ADDED]: SdkEvent.OnBlackAdded,
  [NativeEvent.BLACK_DELETED]: SdkEvent.OnBlackDeleted,
  [NativeEvent.SYNC_SERVER_START]: SdkEvent.OnSyncServerStart,
  [NativeEvent.SYNC_SERVER_FINISH]: SdkEvent.OnSyncServerFinish,
  [NativeEvent.SYNC_SERVER_PROGRESS]: SdkEvent.OnSyncServerProgress,
  [NativeEvent.SYNC_SERVER_FAILED]: SdkEvent.OnSyncServerFailed,
  [NativeEvent.NEW_CONVERSATION]: SdkEvent.OnNewConversation,
  [NativeEvent.CONVERSATION_CHANGED]: SdkEvent.OnConversationChanged,
  [NativeEvent.TOTAL_UNREAD_MESSAGE_COUNT_CHANGED]:
    SdkEvent.OnTotalUnreadMessageCountChanged,
  [NativeEvent.RECV_NEW_MESSAGE]: SdkEvent.OnRecvNewMessage,
  [NativeEvent.RECV_C2C_READ_RECEIPT]: SdkEvent.OnRecvC2CReadReceipt,
  [NativeEvent.RECV_GROUP_READ_RECEIPT]: SdkEvent.OnRecvGroupReadReceipt,
  [NativeEvent.NEW_RECV_MESSAGE_REVOKED]: SdkEvent.OnNewRecvMessageRevoked,
  [NativeEvent.RECV_MESSAGE_EXTENSIONS_CHANGED]:
    SdkEvent.OnRecvMessageExtensionsChanged,
  [NativeEvent.RECV_MESSAGE_EXTENSIONS_DELETED]:
    SdkEvent.OnRecvMessageExtensionsDeleted,
  [NativeEvent.RECV_MESSAGE_EXTENSIONS_ADDED]:
    SdkEvent.OnRecvMessageExtensionsAdded,
  [NativeEvent.RECV_OFFLINE_NEW_MESSAGE]: SdkEvent.OnRecvOfflineNewMessage,
  [NativeEvent.MSG_DELETED]: SdkEvent.OnMsgDeleted,
  [NativeEvent.RECV_NEW_MESSAGES]: SdkEvent.OnRecvNewMessages,
  [NativeEvent.RECV_OFFLINE_NEW_MESSAGES]: SdkEvent.OnRecvOfflineNewMessages,
  [NativeEvent.SELF_INFO_UPDATED]: SdkEvent.OnSelfInfoUpdated,
  [NativeEvent.USER_STATUS_CHANGED]: SdkEvent.OnUserStatusChanged,
  [NativeEvent.RECV_CUSTOM_BUSINESS_MESSAGE]:
    SdkEvent.OnRecvCustomBusinessMessage,
  [NativeEvent.OPEN]: SdkEvent.UnUsedEvent,
  [NativeEvent.PART_SIZE]: SdkEvent.UnUsedEvent,
  [NativeEvent.HASH_PART_PROGRESS]: SdkEvent.UnUsedEvent,
  [NativeEvent.HASH_PART_COMPLETE]: SdkEvent.UnUsedEvent,
  [NativeEvent.UPLOAD_ID]: SdkEvent.UnUsedEvent,
  [NativeEvent.UPLOAD_PART_COMPLETE]: SdkEvent.UnUsedEvent,
  [NativeEvent.UPLOAD_COMPLETE]: SdkEvent.UploadComplete,
  [NativeEvent.COMPLETE]: SdkEvent.UnUsedEvent,
  [NativeEvent.CONVERSATION_USER_INPUT_STATUS_CHANGED]:
    SdkEvent.OnConversationUserInputStatusChanged,
  [NativeEvent.RECV_ONLINE_ONLY_MESSAGE]: SdkEvent.OnRecvOnlineOnlyMessage,
  [NativeEvent.ON_PROGRESS]: SdkEvent.OnUploadLogsProgress,
};
